/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SkyrocketAi {
        "text": string;
    }
}
declare global {
    interface HTMLSkyrocketAiElement extends Components.SkyrocketAi, HTMLStencilElement {
    }
    var HTMLSkyrocketAiElement: {
        prototype: HTMLSkyrocketAiElement;
        new (): HTMLSkyrocketAiElement;
    };
    interface HTMLElementTagNameMap {
        "skyrocket-ai": HTMLSkyrocketAiElement;
    }
}
declare namespace LocalJSX {
    interface SkyrocketAi {
        "text"?: string;
    }
    interface IntrinsicElements {
        "skyrocket-ai": SkyrocketAi;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "skyrocket-ai": LocalJSX.SkyrocketAi & JSXBase.HTMLAttributes<HTMLSkyrocketAiElement>;
        }
    }
}
